name: Move Issue on Pull Request

on:
  pull_request:
    types: [opened]

jobs:

  move-issue:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Move Issue to In Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_URL: https://github.com/maxiboy441/schoolproject-3/projects/1
        IN_REVIEW_COLUMN_NAME: "In review" # Use the column name instead of ID
      run: |
        # Get the linked issue number from the pull request body
        issue_number=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH" | sed -n 's/.*#\([0-9]\+\)/\1/p')
        
        # Get the column ID from the column name
        in_review_column_id=$(gh api $PROJECT_URL/columns --jq '.[] | select(.name == "$IN_REVIEW_COLUMN_NAME") | .id')
        
        # Move the issue to the In Review column
        gh api --header 'Accept: application/vnd.github+json' \
          -X POST /projects/columns/$in_review_column_id/cards \
          -f content_id=${{ github.repository }}/$issue_number \
          -f content_type="Issue"
        
    - name: Add Comment to Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the linked issue number from the pull request body
        issue_number=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH" | sed -n 's/.*#\([0-9]\+\)/\1/p')
        
        # Get a random maintainer from the list of collaborators
        maintainer=$(gh api /repos/${{ github.repository }}/collaborators --jq '.[].login' | shuf -n 1)
        
        # Add a comment to the issue mentioning the maintainer
        gh issue comment $issue_number --body "Hey @$maintainer, can you please review this pull request?"
